version: "3.7"

services:
  my-app:
    image: gym
    environment:
      VIRTUAL_HOST: gym.rikonyberg.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: gym.rikonyberg.com
      # LETSENCRYPT_EMAIL: yero@blog.yerosound.com
    expose:
      - 5000

networks:
  default:
    external:
      name: nginx-proxy